### ISSUE TITLE
ModuleNotFoundError: No module named 'picamera2'

### ISSUE THREAD

**Issue by clive0106** [Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi#24]
I am using 2021-05-07-raspios-buster-armhf as that was the version in your video
Running on a Pi3 b+
When trying to start the server, I am getting

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from Server import *
  File "/home/pi/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server/Server.py", line 8, in <module>
    from picamera2 import Picamera2,Preview
ModuleNotFoundError: No module named 'picamera2'

I have used the camera to take a picture using 
raspistill -o image.jpg

Any ideas?  Should I be using buster?

**Comment by EthanPal** [comment]
Dear customer,

Thank you for choosing Freenove. We are fully responsible for any concerns.

Please use the latest Raspberry Pi OS.

If you have any concerns, please feel free to contact us.

Have a great day!

Best regards,
Shaynee
Freenove Support Team
--------------------------
www.freenove.com 
 
From: Clive Salvidge
Date: 2024-03-28 10:32
To: Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi
CC: Subscribed
Subject: [Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi] ModuleNotFoundError: No module named 'picamera2' (Issue #24)
I am using 2021-05-07-raspios-buster-armhf as that was the version in your video
Running on a Pi3 b+
When trying to start the server, I am getting
Traceback (most recent call last):
File "main.py", line 8, in 
from Server import *
File "/home/pi/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server/Server.py", line 8, in 
from picamera2 import Picamera2,Preview
ModuleNotFoundError: No module named 'picamera2'
I have used the camera to take a picture using
raspistill -o image.jpg
Any ideas? Should I be using buster?
