### ISSUE TITLE
Erro ao executar a camera 

### ISSUE THREAD

**Issue by ar-acvf** [Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi#27]
~/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server $ python camera.py

[0:00:54.741977633] [1947]  INFO Camera camera_manager.cpp:313 libcamera v0.3.0+65-6ddd79b5
Traceback (most recent call last):
  File "/home/arlindo/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server/camera.py", line 2, in <module>
    picam2 = Picamera2()
             ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 246, in __init__
    camera_num = self.global_camera_info()[camera_num]['Num']
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
IndexError: list index out of range

**Comment by Shaynee-MO** [comment]
The error is because the camera cannot be detected.

Please do as follows:
1. Check the wiring. You can send us pictures of the wiring and we will check for you,
![image](https://github.com/user-attachments/assets/cd2fff02-e6a0-44ff-bb97-743213aab682)

2. Follow the tutorial to make configuration.
![image](https://github.com/user-attachments/assets/2131ef3e-42f9-4909-8892-91767689d18d)

3. Reboot your raspberry pi. Run ls /dev/video* to see if the camera can be detected.

If you have any concerns, please feel free to contact us.

Best regards,
Shaynee
Freenove Support Team
--------------------------
www.freenove.com

**Comment by ar-acvf** [comment]
Olá bom dia ao excutar o comando python camera.py
Está dando o seguinte erro ao executar o comando.


[image: image.png]

Em seg., 5 de ago. de 2024 às 02:49, Shaynee ***@***.***>
escreveu:

**Comment by Shaynee-MO** [comment]
Sorry but we cannot see the image. Would you mind sending it again? Many thanks for your help.
