### ISSUE TITLE
Failed to run the command "sudo python Servo.py" 

### ISSUE THREAD

**Issue by SijieDingEsna** [Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi#28]
When I run the command Servo.py. I get the following error:
Now servos will rotate to 90°.
If they have already been at 90°, nothing will be observed.
Please keep the program running when installing the servos.
After that, you can press ctrl-C to end the program.
Traceback (most recent call last):
  File "/home/pi/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server/Servo.py", line 28, in <module>
    S=Servo()
      ^^^^^^^
  File "/home/pi/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server/Servo.py", line 8, in __init__
    self.pwm = PCA9685(address=0x40, debug=True)   
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server/PCA9685.py", line 32, in __init__
    self.write(self.__MODE1, 0x00)
  File "/home/pi/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server/PCA9685.py", line 36, in write
    self.bus.write_byte_data(self.address, reg, value)
OSError: [Errno 5] Input/output error

I use the command "sudo i2cdetect -y 1" to get connected device information. It shows there is no valid device.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- 

I am sure I already enabled i2c and reboot system multiple times.
If you need more information, please let me know.

**Comment by Shaynee-MO** [comment]
Please check the following:
1. Whether connector is connected well.
![image](https://github.com/user-attachments/assets/27ce41b3-a12c-4d19-bd0a-cf951f36f400)


2. Whether both S1 and S2 are turned ON. Do the power and battery indicators light up?

3. Whether the batteries contact well with the battery holder. Please try to push them towards positive end.
![image](https://github.com/user-attachments/assets/2e009d6a-21c6-4ed1-bf92-4a050e58e25a)

**Comment by SijieDingEsna** [comment]
Please see the attached pic of my work. And I already put the batteries into the charger for over 2 nights. 
![IMG_5927](https://github.com/user-attachments/assets/5e6fd20e-ceb2-4911-897f-a85f8b3ee314)
I don't connect any servos on the board. And I think it will not effect the result of i2cdetect. BTW I use wifi to connect raspberry pi with my laptop.

**Comment by Shaynee-MO** [comment]
Please remove the Raspberry Pi and the mpu6050 chip from the robot board.

Connect the MPU6050 chip directly to the raspberry pi and run i2cdetect -y 1 to see if its i2c address can be detected.
![image](https://github.com/user-attachments/assets/eab67d83-8352-4ec1-8f4d-45d76bd8b5d1)
![image](https://github.com/user-attachments/assets/cbfc3c8a-74c6-4e51-aaeb-b31d424ede71)
![image](https://github.com/user-attachments/assets/8def5ca9-f2c7-4035-ae99-b259eff30f35)

**Comment by SijieDingEsna** [comment]
The previous pictures make me confused. The first pic shows 
vcc -> right pin 2nd row
gnd -> right pin 3td row
scl -> left pint 2nd row
sda -> left pin 3td row

The second pic shows
vcc -> right pin 1st row
gnd -> right pin 2nd row
scl -> left pin 2nd row
sda -> left pin 1st row

Would you please tell me which connect method is right?

**Comment by Shaynee-MO** [comment]
Sorry for the confusion it caused. It has to do with the angle of the shot.
![image](https://github.com/user-attachments/assets/28ed3835-df05-4521-b773-3562cf8106df)
![image](https://github.com/user-attachments/assets/a78b01df-797f-4933-97a2-afec400bd0e7)

**Comment by SijieDingEsna** [comment]
I connect with mpu6050 as your guidance. But I still cannot get device by the command "i2cdetect -y 1" .
Please see my connection in the attached pic.
![IMG_5934](https://github.com/user-attachments/assets/c983f7e9-9ea3-4e7b-a49e-58e10050aaa7)

**Comment by Shaynee-MO** [comment]
The issue may be on your Raspberry Pi.
Do you have other control boards such as Arduino and ESP32 to check?

**Comment by SijieDingEsna** [comment]
I don't have other control board. In your mind which board is easier to do such test. I have poor knowledge about it. Thank you

**Comment by Shaynee-MO** [comment]
You can buy an Arduino board.

BTW, you can connect the Raspberry Pi back to the robot board without the mpu6050 chip connected and run i2cdetect -y 1 again to see if it can detect the i2c addresses of other chips.
