### ISSUE TITLE
Issue running the test script

### ISSUE THREAD

**Issue by jdean82** [Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi#30]
I am running on Raspberry Pi 3B+ I have run all the instructions and keep getting the following errors:

:~/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Libs/rpi-ws281x-python/library $ sudo python3 setup.py install
Traceback (most recent call last):
  File "/home/jdean82/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Libs/rpi-ws281x-python/library/setup.py", line 15, in <module>
    setup(name              = 'rpi_ws281x',
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 107, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 75, in _install_setup_requires
    dist = MinimalDistribution(attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 57, in __init__
    super().__init__(filtered)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 473, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1040, in entry_points
    return SelectableGroups.load(eps).select(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 476, in load
    ordered = sorted(eps, key=by_group)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1037, in <genexpr>
    eps = itertools.chain.from_iterable(
                                       ^
  File "/usr/lib/python3.11/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
        ^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 954, in _normalized_name
    or super()._normalized_name
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 627, in _normalized_name
    return Prepared.normalize(self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 882, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I am completely new to coding and have no idea what this means!! Can anyone help? I got the robot dog for christmas and just cant get it to work!

**Comment by jdean82** [comment]
And when I run the test servo script I get the following:
jdean82@JDraspberrypi:~/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server $ sudo python test.py Servo
Traceback (most recent call last):
  File "/home/jdean82/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server/test.py", line 2, in <module>
    from Led import *
  File "/home/jdean82/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server/Led.py", line 4, in <module>
    from rpi_ledpixel import Freenove_RPI_WS281X
  File "/home/jdean82/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Server/rpi_ledpixel.py", line 2, in <module>
    from rpi_ws281x import Adafruit_NeoPixel, Color
ImportError: cannot import name 'Adafruit_NeoPixel' from 'rpi_ws281x' (/usr/local/lib/python3.11/dist-packages/rpi_ws281x-4.3.4-py3.11-linux-aarch64.egg/rpi_ws281x/__init__.py)
